# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install poetry
  - poetry install

# command to run tests using coverage, e.g. python setup.py test
before_script: cd example
script: coverage run --source tips manage.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)
