# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 10:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipOfDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(help_text='The content will be compiled using <a href="http://en.wikipedia.org/wiki/Markdown">Markdown</a>.')),
                ('active', models.BooleanField()),
                ('seen_by', models.ManyToManyField(related_name='seen_tips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
