# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_auto_20160610_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipofday',
            options={'verbose_name': 'tip', 'verbose_name_plural': 'tips'},
        ),
    ]
