# Generated by Django 2.0.1 on 2018-01-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0005_auto_20170124_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipofday',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Only users in these groups will see this tip. If no group is selected, users in all groups can see this tip.', related_name='tips', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='tipofday',
            name='sites',
            field=models.ManyToManyField(blank=True, help_text='Sites to display this tip in. If none is selected, tip will be displayed on all Sites.', to='sites.Site'),
        ),
    ]
